
from twisted.internet import protocol, reactor, endpoints
from twisted.python import log
from config.settings import ICONS_PATH
from core.visualcomponent import VisualComponent
from twisted.internet.endpoints import TCP4ClientEndpoint
from twisted.internet.endpoints import connectProtocol
from core.iconsRegister import getIconFileName
from core.functions import import_and_instantiate_class_from_string
from fabric.api import local
from bresenham import bresenham


# |||||||||||||||||||||||||| MOBILE NETWORK ||||||||||||||||||||||||||


class MobileDevice(object):
    def __init__(self):
        pass


class MobileNetwork(object):

    def __init__(self, simulation_core, wireless_standard, network_layer_protocol, application_layer_protocol, latency):
        self.simulation_core = simulation_core
        self.base_station_list = set()
        self.mobile_repeater_list = set()
        self.mobile_producer_list = set()
        self.network_layer_protocol = network_layer_protocol
        self.application_layer_protocol = application_layer_protocol
        self.wireless_standard = wireless_standard
        self.latency = latency

    # By using this function user can find any device into the mobile network using the if of the draggable image incon.
    # This id is generated by the tkinter canvas. - Rafael Sampaio
    def get_mobile_network_device_by_icon(self, icon_id):
        try:
            founded_device = None
            for device in self.mobile_producer_list:
                if device.visual_component.draggable_img == icon_id:
                    founded_device = device

            for device in self.base_station_list:
                if device.visual_component.draggable_img == icon_id:
                    founded_device = device

            for device in self.mobile_repeater_list:
                if device.visual_component.draggable_img == icon_id:
                    founded_device = device

            if founded_device != None:
                return founded_device

        except Exception as e:
            pass

    def get_mobile_network_device_by_wireless_signal_id(self, wireless_signal_id):
        founded_device = None
        for device in self.mobile_producer_list:
            if device.visual_component.draggable_signal_circle == wireless_signal_id:
                founded_device = device

        for device in self.base_station_list:
            if device.visual_component.draggable_signal_circle == wireless_signal_id:
                founded_device = device

        for device in self.mobile_repeater_list:
            if device.visual_component.draggable_signal_circle == wireless_signal_id:
                founded_device = device

        if founded_device != None:
            return founded_device


class MobileNode(MobileDevice):

    def __init__(self, simulation_core, id, name, icon, is_wireless, x, y, application, coverage_area_radius, mobile_network_group):

        self.application = import_and_instantiate_class_from_string(
            application)
        self.mobile_network_group = mobile_network_group
        self.is_wireless = is_wireless
        self.coverage_area_radius = coverage_area_radius

        icon_file = getIconFileName(icon)
        self.icon = ICONS_PATH+icon_file

        self.name = name+'_'+str(id)
        self.simulation_core = simulation_core

        self.is_wireless = is_wireless
        self.visual_component = VisualComponent(
            self.is_wireless, self.simulation_core, self.name, self.icon, x, y, coverage_area_radius, self)
        self.simulation_core.updateEventsCounter("Initializing mobile node")
        self.application.visual_component = self.visual_component
        self.application.visual_component.coverage_area_radius = coverage_area_radius
        self.application.simulation_core = self.simulation_core
        self.application.coverage_area_radius = coverage_area_radius
        self.application.mobile_network_group = self.mobile_network_group

        if(self.is_wireless == True):
            # setting image tag as "wifi_device" it will be useful when we need to verify if one device under wireless signal can connect to that. - Rafael Sampaio
            self.simulation_core.canvas.itemconfig(
                self.visual_component.draggable_img, tags=("wifi_device",))

    def run(self):
        self.application.start()


class BaseStationNode(MobileDevice):

    def __init__(self, simulation_core, id, name, icon, is_wireless, x, y, application, coverage_area_radius, mobile_network_group, mqtt_destiny_topic):

        self.application = import_and_instantiate_class_from_string(
            application)
        self.mobile_network_group = mobile_network_group
        self.is_wireless = is_wireless
        self.coverage_area_radius = coverage_area_radius

        icon_file = getIconFileName(icon)
        self.icon = ICONS_PATH+icon_file

        self.name = name+'_'+str(id)
        self.id = id
        self.simulation_core = simulation_core

        self.is_wireless = is_wireless
        self.visual_component = VisualComponent(
            self.is_wireless, self.simulation_core, self.name, self.icon, x, y, coverage_area_radius, self)
        self.simulation_core.updateEventsCounter(
            "Initializing mobile network base station node")
        self.application.visual_component = self.visual_component
        self.application.simulation_core = self.simulation_core
        self.application.mqtt_destiny_topic = mqtt_destiny_topic

        if(self.is_wireless == True):
            # setting image tag as "wifi_device" it will be useful when we need to verify if one device under wireless signal can connect to that. - Rafael Sampaio
            self.simulation_core.canvas.itemconfig(
                self.visual_component.draggable_img, tags=("wifi_device",))

    def run(self):
        self.application.start()

# |||||||||||||||||||||||||| END MOBILE NETWORK ||||||||||||||||||||||||||
