{
    "fog_nodes": [
        { 
            "id": 1,
            "name": "Fog Subscriber Node", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "server_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.SubscriberApp",
            "x": 550,
            "y": 175
        },
        { 
            "id": 2,
            "name": "Fog Broker Node", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "server_icon",
            "type": "server",
            "port": 5100,
            "is_wireless": false,
            "application": "applications.mqttapp.BrokerApp",
            "x": 250,
            "y": 175
        }
    ],
    "cloud_nodes": [
        
    ],
    "iot_nodes": [
        {
            "id": 5,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 170,
            "y": 380
        },
        {
            "id": 6,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 370,
            "y": 395
        },
        {
            "id": 7,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 495
        },
        {
            "id": 8,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 570,
            "y": 495
        },
        {
            "id": 9,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 295
        },
        {
            "id": 10,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 389,
            "y": 200
        },
        {
            "id": 11,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 270,
            "y": 380
        },
        {
            "id": 12,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 270,
            "y": 395
        },
        {
            "id": 13,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 495
        },
        {
            "id": 14,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 270,
            "y": 495
        },
        {
            "id": 15,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 670,
            "y": 295
        },
        {
            "id": 16,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 589,
            "y": 200
        },
        {
            "id": 17,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 370,
            "y": 380
        },
        {
            "id": 18,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 370,
            "y": 395
        },
        {
            "id": 19,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 570,
            "y": 495
        },
        {
            "id": 22,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 370,
            "y": 495
        },
        {
            "id": 23,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 770,
            "y": 295
        },
        {
            "id": 24,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 689,
            "y": 200
        },
        {
            "id": 25,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 380
        },
        {
            "id": 26,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 395
        },
        {
            "id": 27,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 670,
            "y": 495
        },
        {
            "id": 28,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 495
        },
        {
            "id": 29,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 870,
            "y": 295
        },
        {
            "id": 30,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 689,
            "y": 200
        },
        {
            "id": 31,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 495
        },
        {
            "id": 32,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 670,
            "y": 595
        },
        {
            "id": 33,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 595
        },
        {
            "id": 34,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 870,
            "y": 395
        },
        {
            "id": 35,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 689,
            "y": 300
        },
        {
            "id": 36,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 595
        },
        {
            "id": 37,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 870,
            "y": 395
        },
        {
            "id": 38,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 689,
            "y": 300
        },
        {
            "id": 39,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 595
        },
        {
            "id": 40,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 670,
            "y": 695
        },
        {
            "id": 41,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 695
        },
        {
            "id": 42,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 870,
            "y": 495
        },
        {
            "id": 43,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 689,
            "y": 400
        },
        {
            "id": 44,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 695
        },
        {
            "id": 45,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 670,
            "y": 795
        },
        {
            "id": 46,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 795
        },
        {
            "id": 47,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 870,
            "y": 595
        },
        {
            "id": 48,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 689,
            "y": 500
        },
        {
            "id": 49,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 170,
            "y": 380
        },
        {
            "id": 50,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 370,
            "y": 395
        },
        {
            "id": 51,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 495
        },
        {
            "id": 52,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 570,
            "y": 495
        },
        {
            "id": 53,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 295
        },
        {
            "id": 54,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 389,
            "y": 200
        },
        {
            "id": 55,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 270,
            "y": 380
        },
        {
            "id": 56,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 270,
            "y": 395
        },
        {
            "id": 57,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 495
        },
        {
            "id": 58,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 270,
            "y": 495
        },
        {
            "id": 59,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 670,
            "y": 295
        },
        {
            "id": 60,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 589,
            "y": 200
        },
        {
            "id": 61,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 370,
            "y": 380
        },
        {
            "id": 62,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 370,
            "y": 395
        },
        {
            "id": 63,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 570,
            "y": 495
        },
        {
            "id": 64,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 370,
            "y": 495
        },
        {
            "id": 65,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 770,
            "y": 295
        },
        {
            "id": 66,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 689,
            "y": 200
        },
        {
            "id": 67,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 380
        },
        {
            "id": 68,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 395
        },
        {
            "id": 69,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 670,
            "y": 495
        },
        {
            "id": 70,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 495
        },
        {
            "id": 71,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 870,
            "y": 295
        },
        {
            "id": 72,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 689,
            "y": 200
        },
        {
            "id": 73,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 495
        },
        {
            "id": 74,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 670,
            "y": 595
        },
        {
            "id": 75,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 595
        },
        {
            "id": 76,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 870,
            "y": 395
        },
        {
            "id": 77,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 689,
            "y": 300
        },
        {
            "id": 78,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 595
        },
        {
            "id": 79,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 870,
            "y": 395
        },
        {
            "id": 80,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 689,
            "y": 300
        },
        {
            "id": 81,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 595
        },
        {
            "id": 82,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 670,
            "y": 695
        },
        {
            "id": 83,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 695
        },
        {
            "id": 84,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 870,
            "y": 495
        },
        {
            "id": 85,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 689,
            "y": 400
        },
        {
            "id": 86,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 695
        },
        {
            "id": 87,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 670,
            "y": 795
        },
        {
            "id": 88,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 795
        },
        {
            "id": 89,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 870,
            "y": 595
        },
        {
            "id": 90,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 689,
            "y": 500
        },
        {
            "id": 91,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 695
        },
        {
            "id": 92,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 670,
            "y": 795
        },
        {
            "id": 93,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 795
        },
        {
            "id": 94,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 870,
            "y": 595
        },
        {
            "id": 95,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 689,
            "y": 500
        },
        {
            "id": 96,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 670,
            "y": 795
        },
        {
            "id": 97,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 470,
            "y": 795
        },
        {
            "id": 98,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 870,
            "y": 595
        },
        {
            "id": 99,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 689,
            "y": 500
        },
        {
            "id": 100,
            "name": "Arduino based sensor (publisher node)", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "arduino_uno_icon",
            "type": "client",
            "is_wireless": false,
            "application": "applications.mqttapp.PublisherApp",
            "x": 689,
            "y": 500
        }
    ],
    "access_points": [
        { 
            "id": 4,
            "TBTT": 0.1024,
            "SSID": "Rede privada 001",
            "WPA2_password": "iotfogsim2019",
            "simulation_ip": "192.121.0.1",
            "icon": "ap_icon",
            "type": "access_point",
            "is_wireless": true,
            "x": 400,
            "y": 300
        } 
    ],
    "routers": [
        { 
            "id": 3,
            "name": "Router 001", 
            "simulation_ip": "192.121.0.1",
            "real_ip": "127.0.0.1",
            "icon": "router_icon",
            "type": "router",
            "port": 8081,
            "application": "applications.routerapp.RouterApp",
            "is_wireless": false,
            "x": 400,
            "y": 200
        }
    ]
}